namespace TravelPal
{
    public enum EuropeanCountry
    {
        Austria,
        Belgium,
        Bulgaria,
        Croatia,
        Cyprus,
        Denmark,
        Portugal,
        Romania,
        Slovakia,
        Slovenia,
        Spain,
        Sweden
    }
    public enum Country
    {
        Argentina,
        Australia,
        Brazil,
        China,
        England,
        Iceland,
        India,
        Japan,
        Russia,
        Thailand,
        USA,
        Vietnam,
        Austria,
        Belgium,
        Bulgaria,
        Croatia,
        Cyprus,
        Denmark,
        Portugal,
        Romania,
        Slovakia,
        Slovenia,
        Spain,
        Sweden
    }
}
